# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [1]:
import numpy as np


### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [3]:
A = np.arange(1, 16).reshape(3,5)

In [8]:
print(f' Shape: {A.shape}')
print(f' Data type: {type(A)}')

 Shape: (3, 5)
 Data type: <class 'numpy.ndarray'>


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [9]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)


[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [19]:
# Elementwise subtraction. 
D = np.subtract(B, C)
print(D)

[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]


In [20]:
# Elementwise multiplication. 
E = np.multiply(B, C)
print(E)


[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]


In [21]:
# Matrix multiplication (by default you should use the @ operator).
F = B @ C
print(F)

[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [18]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [23]:
# * Exponentiate each number elementwise (use the np.exp function).
C = np.exp(B)
print(C)

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]


In [24]:
# * Calculate the minimum value in the whole matrix.
min_B = np.min(B)
print(min_B)

1


In [26]:
# * Calculcate the minimum value in each row. 
min_B_row = np.min(B, axis=1)
print(min_B_row)

[1 4 7]


In [27]:

# * Calculcate the minimum value in each column. 
min_B_col = np.min(B, axis=0)
print(min_B_col)

[1 2 3]


In [28]:
# * Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
min_B_index = np.argmin(B)
print(min_B_index)

0


In [29]:
# * Find the index value for the minimum value in each row (hint: use np.argmin).
min_ind_row = np.argmin(B, axis=1)
print(min_ind_row)

[0 0 0]


In [30]:
# * Calculate the sum for all elements.

sum_B = np.sum(B)
print(sum_B)

45


In [31]:
# * Calculate the mean for each column. 

mean_col = np.mean(B, axis=0)
print(mean_col)

[4. 5. 6.]


In [32]:
# * Calculate the median for each column. 
median_col = np.median(B, axis=0)
print(median_col)

[4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [33]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [34]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

It seems like this selects all elements along the second row (index 1), and apparently it assumes the column index to be ":", 
thus returning an element in each column of the array

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [36]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [37]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [40]:
# use A.flat to convert the array into a 1-dimensional matrix
for i in A.flat: 

    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [45]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


#### the code above produces a 3 dimensional array (b), from the 30 elements of (a). the first dimension has 2 elements, the second has 3 elements, and the third is determined automatically from the number of elements (argument -1). so the third dimension is 30/(2x3) = 5. 

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [46]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [47]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [48]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [49]:
def add_mult_matrices(arr1, arr2, mat_operation):
  """Function to add or multiply two matrices.

  Inputs: 
    arr1, arr2: The 2 matrices
    mat_operation: option to specify matrix operation ('add' or 'multiply')

  Returns:
    The result of the operation.
  """

  if not isinstance(arr1, np.ndarray) or not isinstance(arr2, np.ndarray):
    raise TypeError("input matrices provided are not numpy arrays.")

  if mat_operation not in ('add', 'multiply'):
    raise ValueError("Strictly choose either 'add' or 'multiply' only.")

  if mat_operation == 'add':
    #check if matrices have same shape for addition
    if arr1.shape != arr2.shape:
      raise ValueError("Input matrices must have the same shape!")
    return arr1 + arr2
  else:
    if mat_operation == 'multiply':
    #check if number of columns in the first matrix is equal to the number of rows in the second matrix
        if arr1.shape[1] != arr2.shape[0]:
            raise ValueError("number of columns in the first matrix must equal to the number of rows in the second matrixfor multiplication.")
        return np.dot(arr1, arr2)

### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

In [6]:
# import image module 
from IPython.display import Image
# Uppgift 10.1.1
Image(url="uppgif_10_1_1.jpg", width=400, height=400) 


In [80]:
## Definiera X
X = np.array([[4, 3]])
print(X)

[[4 3]]


(a) X är en rad matrix, with en rad och en 2 columner, i.e. en 1x2 matrix

In [15]:
# (b) beräkna 5X

X5 = 5 * X
print(X5)


[[20 15]]


In [16]:
# (c) beräkna 3X

X3 = 3 * X
print(X3)

[[12  9]]


In [17]:
# (d) beräkna 5X + 3X
sum_5X_3X = X5 + X3
print(sum_5X_3X)

[[32 24]]


In [18]:
# (e) beräkna 8X
X8 = 8 * X
print(X8)

[[32 24]]


In [19]:
# (f) beräkna 4X - X

X4 = 4*X
x4_min_X = X4 - X
print(x4_min_X)

[[12  9]]


In [66]:
# (g) beräkna X transpose
X_transposed = X.T
print(X_transposed)

[[4]
 [3]]


In [81]:
#(h)
# Mathematically, matrix addition is defined for matrices of the same shape, thus X + X_transposed would be undefined. 
# However, NumPy uses broadcasting to make the shapes compatible for addition, by replicating the smaller (1x2) matrix along the missing dimension
# in order to match the larger matrix (2x1). once replicated, both matrices have similar dimensions and thus their sum is defined.

np.seterr(over='warn') # catch warnings for the behavior behaviour (a warning msg appears in console!)

sum_X_XT = X + X_transposed
print(sum_X_XT)

[[8 7]
 [7 6]]


In [38]:
# (i) beräkna ||X||
norm_X = np.linalg.norm(X) #calculate the Frobenius norm (default norm in numpy)
print("Frobenius norm:", norm_X) 

Frobenius norm: 5.0


In [26]:
# Uppgift 10.1.2
Image(url="uppgif_10_1_2.jpg", width=400, height=400) 

In [29]:
# Define vector v (4x1)
v = np.array([[3],[7],[0],[11]])

#(a)  vector v dimensions
print(v.shape) # The vector v has 4 x 1 dimension (4 rows / 1 column)

(4, 1)


In [30]:
#(b)  beräkna 2v

v2 = 2*v
print(v2)

[[ 6]
 [14]
 [ 0]
 [22]]


In [31]:
#(c)  beräkna 5v + 2v
v5 = 5*v
v5_p_2v = v5 + v2
print(v5_p_2v)

[[21]
 [49]
 [ 0]
 [77]]


In [34]:
#(d)  beräkna 4v - 2v
v4_m_2v = 4*v - v2 # Should be equal to 2v
print(v4_m_2v)
print(v4_m_2v == v2)

[[ 6]
 [14]
 [ 0]
 [22]]
[[ True]
 [ True]
 [ True]
 [ True]]


In [35]:
#(e)  v transpose

v_T = v.T
print(v_T.shape) # the transpose of v is a 1 by 4 matrix 

(1, 4)


In [37]:
# (f) beräkna ||v||
norm_v = np.linalg.norm(v) #calculates the Frobenius norm (default norm in numpy)
print("Frobenius norm:", norm_v) 

Frobenius norm: 13.379088160259652


In [41]:
# Uppgift 10.1.3

# define v1 and v2

v1 = np.array([[4, 3, 1, 5]])
v2 = np.array([[2, 3, 1, 1]])
print (v1.shape)
print(v2.shape)


(1, 4)
(1, 4)


In [42]:
# (a) beräkna ||v1||
norm_v1 = np.linalg.norm(v1) #calculates the Frobenius norm (default norm in numpy)
print("Frobenius norm:", norm_v1) 

Frobenius norm: 7.14142842854285


In [44]:
# (a) beräkna ||v1 - v2||

norm_v1_2 = np.linalg.norm((v1-v2)) #calculates the Frobenius norm (default norm in numpy)
print("Frobenius norm:", norm_v1_2) 

# same as calculating the normal of the the difference matrix v1-v2
v1_2 = v1-v2
norm_v1_2_2 = np.linalg.norm(v1_2) #calculates the Frobenius norm (default norm in numpy)
print("Frobenius norm:", norm_v1_2_2) 

Frobenius norm: 4.47213595499958
Frobenius norm: 4.47213595499958


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

In [47]:
# Uppgift 10.2
Image(url="uppgif_10_2_1.jpg", width=400, height=400) 

In [57]:
# Define Matrice A, B, C, D, E and I
A = np.array([[2, 1,-1],[1, -1,1] ])
print ("Matrix A dimensions: ", A.shape)

B = np.array([[4, -2, 1],[2, -4, -2] ])
print ("Matrix B dimensions: ", B.shape)

C = np.array([[1, 2],[2, 1] ])
print ("Matrix C dimensions: ", C.shape)

D = np.array([[3, 4],[4, 3] ])
print ("Matrix D dimensions: ", D.shape)

E = np.array([[1],[2] ])
print ("Matrix E dimensions: ", E.shape)

I = np.array([[1, 0],[0, 1] ])
print ("Matrix I dimensions: ", I.shape)

Matrix A dimensions:  (2, 3)
Matrix B dimensions:  (2, 3)
Matrix C dimensions:  (2, 2)
Matrix D dimensions:  (2, 2)
Matrix E dimensions:  (2, 1)
Matrix I dimensions:  (2, 2)


In [56]:
# (a) 2A
A2 = 2*A # defined (scalar multiplication)
print("A = ", A, " \n 2A = ", A2)

A =  [[ 2  1 -1]
 [ 1 -1  1]]  
 2A =  [[ 4  2 -2]
 [ 2 -2  2]]


In [58]:
# (b) B -2A (defined, B & A have same dimensions (2x3)

B_2A = B - 2*A
print(B_2A)

[[ 0 -4  3]
 [ 0 -2 -4]]


In [79]:
# (c) 3C -2E (undefined, C (2x2) & E (2,1). However, thanks to numpy broadcasting process, this operation can be done. 
np.seterr(over='warn') # catch warnings for the behavior behaviour (a warning msg appears in console!)
C3_2E = 3*C -2*E
print(C3_2E)

[[ 1  4]
 [ 2 -1]]


In [73]:
# (d) 2D -3C (defined, D & C have same dimensions (2x2)

D2_3C = 2*D -3*C
print(D2_3C)

[[3 2]
 [2 3]]


In [63]:
# (e) D_T + 2D (defined, D & D_T have same dimensions (2x2)

DT_2D = D.T + 2*D
print("DT+2D = ", DT_2D)

DT+2D =  [[ 9 12]
 [12  9]]


In [64]:
# (f) 2C_T - 2D_T  (defined, C_T & D_T have same dimensions (2x2)
C2_T_2D_T = 2*C.T - 2*D.T
print(C2_T_2D_T)

[[-4 -4]
 [-4 -4]]


In [92]:
# (g) A_T - B  (defined, A_T is a 2x2, and B is 2x3, i.e. number of columns in first matrix is equal to the number of rows in the second matrix

A_T_B = A.T @ B
print(A_T_B)


[[10 -8  0]
 [ 2  2  3]
 [-2 -2 -3]]


In [94]:
# (h) AC ( Not defined A(2x3) & C(2x2), number of columns in first matrix must be equal to the number of rows in the second matrix)


In [99]:
#(i) AD ( Not defined A(2x3) & D(2x2), number of columns in first matrix must be equal to the number of rows in the second matrix )


In [96]:
# (j) CB ( Defined C(2x2) & B(2x3), number of columns in first matrix must be equal to the number of rows in the second matrix )
print(C.shape)
print(B.shape)
CB = C @ B

print(CB)

(2, 2)
(2, 3)
[[  8 -10  -3]
 [ 10  -8   0]]


In [100]:
# (k) CI (defined, C is a 2x2, and I is 2x2, i.e. number of columns in first matrix is equal to the number of rows in the second matrix

C @ I


array([[1, 2],
       [2, 1]])

In [101]:
# (l) AB_T (defined, A is a 2x3, and B_T is 3x2, i.e. number of columns in first matrix is equal to the number of rows in the second matrix

A @ B.T

array([[5, 2],
       [7, 4]])

In [48]:
Image(url="uppgif_10_2_2.jpg", width=400, height=400) 

### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [50]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [51]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [52]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]
